# Generated by Django 5.2.1 on 2025-05-26 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_data", models.BinaryField()),
                ("vectorizer_data", models.BinaryField()),
                ("accuracy", models.FloatField(default=0.0)),
                ("total_sessions", models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name="listing",
            old_name="kept",
            new_name="is_keeper",
        ),
        migrations.AddField(
            model_name="listing",
            name="predicted_keeper",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="RecommendationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accuracy", models.FloatField(default=0.0)),
                ("num_correct", models.IntegerField(default=0)),
                ("num_total", models.IntegerField(default=0)),
                ("session_data", models.JSONField(default=dict)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discogs.recommendationmodel",
                    ),
                ),
            ],
        ),
    ]
