# Generated by Django 5.2.1 on 2025-05-26 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discogs", "0002_recommendationmodel_rename_kept_listing_is_keeper_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="is_keeper",
            new_name="kept",
        ),
        migrations.RenameField(
            model_name="recommendationmodel",
            old_name="accuracy",
            new_name="last_accuracy",
        ),
        migrations.RemoveField(
            model_name="recommendationmodel",
            name="total_sessions",
        ),
        migrations.AddField(
            model_name="recommendationmodel",
            name="feature_names",
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name="RecommendationMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.DateTimeField(auto_now_add=True)),
                ("accuracy", models.FloatField()),
                ("precision", models.FloatField()),
                ("num_samples", models.IntegerField()),
                (
                    "recommendation_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="discogs.recommendationmodel",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="RecommendationSession",
        ),
    ]
