# Generated by Django 5.2.1 on 2025-05-26 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discogs", "0003_rename_is_keeper_listing_kept_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recommendationmetrics",
            options={"ordering": ["-session_date"]},
        ),
        migrations.RemoveField(
            model_name="recommendationmetrics",
            name="recommendation_model",
        ),
        migrations.AlterField(
            model_name="recommendationmetrics",
            name="accuracy",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="recommendationmetrics",
            name="num_samples",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="recommendationmetrics",
            name="precision",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="recommendationmetrics",
            name="session_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="recommendationmodel",
            name="model_data",
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name="recommendationmodel",
            name="vectorizer_data",
            field=models.BinaryField(null=True),
        ),
    ]
