# Generated by Django 5.2.1 on 2025-05-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discogs", "0004_alter_recommendationmetrics_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recommendationmetrics",
            options={},
        ),
        migrations.AddField(
            model_name="recommendationmetrics",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="recommendationmetrics",
            name="accuracy",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="recommendationmetrics",
            name="num_samples",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="recommendationmetrics",
            name="precision",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="recommendationmetrics",
            name="session_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="recommendationmodel",
            name="model_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recommendationmodel",
            name="vectorizer_data",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
