# Generated by Django 5.2.1 on 2025-05-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discogs", "0005_alter_recommendationmetrics_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationmodel",
            name="model_version",
            field=models.CharField(default="v1.0", max_length=50),
        ),
        migrations.AddField(
            model_name="recommendationmodel",
            name="scaler_data",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
