# Generated by Django 5.2.1 on 2025-06-04 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discogs", "0006_recommendationmodel_model_version_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordOfTheDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("model_score", models.FloatField()),
                ("entropy_measure", models.FloatField()),
                ("system_temperature", models.FloatField()),
                ("utility_term", models.FloatField()),
                ("entropy_term", models.FloatField()),
                ("free_energy", models.FloatField()),
                ("selection_probability", models.FloatField()),
                ("total_candidates", models.IntegerField()),
                ("cluster_count", models.IntegerField(default=0)),
                (
                    "selection_method",
                    models.CharField(default="thermodynamic_boltzmann", max_length=50),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discogs.listing",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
