# Generated by Django 5.2.1 on 2025-06-06 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discogs", "0007_recordoftheday"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordoftheday",
            name="average_novelty",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="recordoftheday",
            name="desirability_votes",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="recordoftheday",
            name="novelty_votes",
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name="RecordOfTheDayFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "desirability_rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "novelty_rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record_of_the_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="discogs.recordoftheday",
                    ),
                ),
            ],
        ),
    ]
