# Generated by Django 5.2.1 on 2025-06-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discogs", "0008_recordoftheday_average_desirability_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordoftheday",
            name="average_desirability",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="recordoftheday",
            name="cluster_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recordoftheday",
            name="entropy_term",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recordoftheday",
            name="free_energy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recordoftheday",
            name="selection_probability",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recordoftheday",
            name="total_candidates",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recordoftheday",
            name="utility_term",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
